[package]
name = "amethyst-rhusics"
version = "0.1.0"
authors = ["Simon Rönnberg <seamonr@gmail.com>"]

repository = "https://github.com/amethyst/amethyst-rhusics.git"
homepage = "https://github.com/amethyst/amethyst-rhusics.git"

license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/amethyst-rhusics"
description = "Integration of `amethyst` and `rhusics`"

keywords = ["gamedev", "amethyst", "physics"]

[dependencies]
amethyst_core = { version = "0.1.0", git = "https://github.com/amethyst/amethyst", branch = "develop" }
rhusics-ecs = { version = "0.1", git = "https://github.com/rustgd/rhusics", branch = "fix/update-collision", features = ["eders"] }
rhusics-core = { version = "0.1", git = "https://github.com/rustgd/rhusics", branch = "fix/update-collision", features = ["specs", "eders"] }
specs = "0.10"
shrev = "0.8"
collision = { version = "0.14", git = "https://github.com/rustgd/collision-rs", branch = "feature/more-primitives" }

[dev-dependencies]
amethyst = { version = "0.6.0", git = "https://github.com/amethyst/amethyst", branch = "develop" }
genmesh = "0.5"
rand = "0.3"
