[package]
name = "amethyst-rhusics"
version = "0.1.0"
authors = []

[dependencies]
amethyst_core = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
rhusics-ecs = { version = "0.1", features = ["eders"] }
rhusics-core = { version = "0.1", features = ["specs", "eders"] }
specs = "0.10"
shrev = "0.8"
collision = "0.14"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
genmesh = "0.5"
rand = "0.3"

[[example]]
name = "boxes2d"
path = "examples/boxes2d/main.rs"