[package]
name = "amethyst-rhusics"
version = "0.1.0"
authors = ["Simon Rönnberg <seamonr@gmail.com>"]

repository = "https://github.com/amethyst/amethyst-rhusics.git"
homepage = "https://github.com/amethyst/amethyst-rhusics.git"

license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/amethyst-rhusics"
description = "Integration of `amethyst` and `rhusics`"

keywords = ["gamedev", "amethyst", "physics"]

[dependencies]
amethyst_core = { version = "0.1.0", git = "https://github.com/amethyst/amethyst", branch = "develop" }
amethyst_renderer = { version = "0.6.1", git = "https://github.com/amethyst/amethyst", branch = "develop" }
rhusics-ecs = { version = "0.4.0-alpha1", features = ["eders"], git = "https://github.com/rustgd/rhusics" }
rhusics-core = { version = "0.4.0-alpha1", features = ["specs", "eders"], git = "https://github.com/rustgd/rhusics" }
specs = "0.11.0-alpha5"
shrev = "0.8"
collision = { version = "0.16", features = ["eders"]}

[dev-dependencies]
amethyst = { version = "0.6.0", git = "https://github.com/amethyst/amethyst", branch = "develop" }
genmesh = "0.5"
rand = "0.3"
shred = "0.7.0-alpha5"
shred-derive = "0.5.0-alpha1"

[patch.crates-io]
coreaudio-sys = { git = "https://github.com/regexident/coreaudio-sys.git", branch = "frameworks" }
