[package]
name = "amethyst_rhusics"
version = "0.1.0"
authors = []

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
rhusics = { git = "https://github.com/dkushner/rhusics", branch = "rigid-body-physics", features = ["ecs"] }
shrev = "0.6"
genmesh = "0.5"
rand = "0.3"

[[example]]
name = "boxes2d"
path = "examples/boxes2d/main.rs"

[[example]]
name = "boxes3d"
path = "examples/boxes3d/main.rs"
