[package]
name = "amethyst-rhusics"
version = "0.3.2"
authors = ["Simon Rönnberg <seamonr@gmail.com>"]
edition = "2018"

repository = "https://github.com/amethyst/amethyst-rhusics.git"
homepage = "https://github.com/amethyst/amethyst-rhusics.git"

license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/amethyst-rhusics"
description = "Integration of `amethyst` and `rhusics`"

keywords = ["gamedev", "amethyst", "physics"]

[dependencies]
amethyst_error = { git = "https://github.com/amethyst/amethyst"}
amethyst_core = { git = "https://github.com/amethyst/amethyst"}
amethyst_renderer = { git = "https://github.com/amethyst/amethyst"}
rhusics-ecs = { version = "*", features = ["serde"] }
rhusics-core = { version = "*", features = ["specs", "serde"] }
shrev = "*"
collision = { version = "0.18", features = ["serde"]}
nalgebra = "*"
cgmath = "0.16"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst" }
genmesh = "*"
rand = "0.5"
shred = "*"
shred-derive = "*"
