[package]
name = "amethyst-rhusics"
version = "0.1.0"
authors = ["Simon Rönnberg <seamonr@gmail.com>"]

repository = "https://github.com/amethyst/amethyst-rhusics.git"
homepage = "https://github.com/amethyst/amethyst-rhusics.git"

license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/amethyst-rhusics"
description = "Integration of `amethyst` and `rhusics`"

keywords = ["gamedev", "amethyst", "physics"]

[dependencies]
amethyst_core = { version = "0.1.0", git = "https://github.com/amethyst/amethyst", branch = "develop" }
amethyst_renderer = { version = "0.6.1", git = "https://github.com/amethyst/amethyst", branch = "develop" }
rhusics-ecs = { version = "0.4.0-alpha3", features = ["serde"] }
rhusics-core = { version = "0.4.0-alpha3", features = ["specs", "serde"] }
specs = "0.11.0-alpha7"
shrev = "1.0.1"
collision = { version = "0.18", features = ["serde"]}

[dev-dependencies]
amethyst = { version = "0.6.0", git = "https://github.com/amethyst/amethyst", branch = "develop" }
genmesh = "0.5"
rand = "0.3"
shred = "0.7.0-alpha6"
shred-derive = "0.5.0-alpha2"

[patch.crates-io]
coreaudio-sys = { git = "https://github.com/RustAudio/coreaudio-sys.git" }
collision = { git = "https://github.com/rustgd/collision-rs", branch = "feature/smallvec" }
rhusics-core = { git = "https://github.com/rustgd/rhusics", branch = "fix/update-deps" }
rhusics-ecs = { git = "https://github.com/rustgd/rhusics", branch = "fix/update-deps" }
