[package]
name = "amethyst-rhusics"
version = "0.1.0"
authors = ["Simon Rönnberg <seamonr@gmail.com>"]

repository = "https://github.com/amethyst/amethyst-rhusics.git"
homepage = "https://github.com/amethyst/amethyst-rhusics.git"

license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/amethyst-rhusics"
description = "Integration of `amethyst` and `rhusics`"

keywords = ["gamedev", "amethyst", "physics"]

[dependencies]
amethyst_core = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
rhusics-ecs = { git = "https://github.com/Rhuagh/rhusics", features = ["eders"] }
rhusics-core = { git = "https://github.com/Rhuagh/rhusics", features = ["specs", "eders"] }
specs = "0.10"
shrev = "0.8"
collision = "0.14"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
genmesh = "0.5"
rand = "0.3"

[[example]]
name = "boxes2d"
path = "examples/boxes2d/main.rs"